version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

  background-tasks:
    build:
      context: .
      dockerfile: Dockerfile.background-tasks
    depends_on:
      - postgres
      - redis
    ports:
      - "8082:8080"

  central-auth:
    build:
      context: .
      dockerfile: Dockerfile.central-auth
    depends_on:
      - postgres
      - redis
    ports:
      - "8083:8080"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: booking
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6380:6379"

volumes:
  postgres_data: